language: node_js
node_js:
    - "6"
before_script:
    - npm run lint
script:
    - npm run test-coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_script:
    - npm run code-verification
